<?php

namespace AppBundle\Repository;

/**
 * AlbumGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
