<?php

namespace AppBundle\Repository;

/**
 * CategoriePartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePartenaireRepository extends \Doctrine\ORM\EntityRepository {

    public function findScallar() {
        $query = $this->_em->createQuery("select c.libelle, c.id" .
                " from AppBundle:CategoriePartenaire c" .
                " order by c.libelle desc"
        );
        return $query->getScalarResult();
    }

}
