<?php

namespace AppBundle\Repository;

/**
 * CategorieActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieActualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
