<?php

namespace AppBundle\Repository;

/**
 * DistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributeurRepository extends \Doctrine\ORM\EntityRepository
{
}
