<?php

namespace AppBundle\Repository;

/**
 * ImageAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
