<?php

namespace AppBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParents() {
        return $this->_em->createQuery('Select m ' .
                                       'from AppBundle:Menu m ' .
                                       'where m.parent is null ' .
                                       'order by m.position asc'
                                        )
                                        ->getResult();
    }
    
    public function getFils($menu) {
        return $this->_em->createQuery('Select m ' .
                                       'from AppBundle:Menu m ' .
                                       'join m.parent p ' .
                                       'where p.id = :id ' .
                                       'order by m.position asc'
                                        )
                                        ->setParameter('id', $menu->getId())
                                        ->getResult();
    }
    
    public function getMenuArbre() {
        $menuArbre = [];
        $parents = $this->getParents();
        foreach ($parents as $parent) {
            $menuArbre[] = ["menu" => $parent, "arbre" => $this->getArbre($parent) ];
        }
        return $menuArbre;
    }

    public function getArbre($parent) {
        $arbre = [];
        foreach ($this->getFils($parent) as $fils) {
            $arbre[] = ['menu' => $fils, 'arbre' => $this->getArbre($fils)];
        }
        return $arbre;
    }

}
