<?php

namespace AppBundle\Repository;

/**
 * OpportuniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportuniteRepository extends \Doctrine\ORM\EntityRepository
{
}
