<?php

namespace AppBundle\Repository;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends \Doctrine\ORM\EntityRepository {

    public function findScallar() {
        $query = $this->_em->createQuery("select c.libelle as cat_lib, s.id, p.nom, p.image" .
                " from AppBundle:Partenaire p" .
                " join p.categoriePartenaire c" .
                " order by c.libelle desc"
        );
        return $query->getScalarResult();
    }

}
