<?php

namespace AppBundle\Repository;

/**
 * ProfilDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
