<?php

namespace AppBundle\Repository;

/**
 * ProfilUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
