<?php

namespace AppBundle\Repository;

/**
 * SlidesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidesRepository extends \Doctrine\ORM\EntityRepository
{
}
