<?php

namespace AppBundle\Repository;

/**
 * SousTypeDistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeDistributeurRepository extends \Doctrine\ORM\EntityRepository
{
}
