<?php

namespace AppBundle\Repository;

/**
 * TypeDistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDistributeurRepository extends \Doctrine\ORM\EntityRepository
{
}
