<?php

namespace AppBundle\Repository;

/**
 * TypeOpportuniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOpportuniteRepository extends \Doctrine\ORM\EntityRepository
{
}
