app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /admin

site:
    resource: "@SiteBundle/Controller/"
    type: annotation
    prefix:   /
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"